plugins {
    id 'com.android.library'
}

android {
    namespace 'info.guardianproject.netcipher'

    buildToolsVersion = signalBuildToolsVersion
    compileSdkVersion = signalCompileSdkVersion

    defaultConfig {
        minSdk = signalMinSdkVersion
        targetSdk = signalTargetSdkVersion
    }

    compileOptions {
        sourceCompatibility signalJavaVersion
        targetCompatibility signalJavaVersion
        coreLibraryDesugaringEnabled true
    }
}

dependencies {
    coreLibraryDesugaring libs.android.tools.desugar
    androidTestImplementation libs.android.tools.desugar
    implementation project(':core-util')
    implementation libs.androidx.fragment
    lintChecks project(':lintchecks')
}
