org.gradle.jvmargs=-Xmx5g -XX:+UseParallelGC
org.gradle.parallel=true
kotlin.daemon.jvmargs=-Xmx6g -XX:+UseG1GC
android.useAndroidX=true
org.gradle.configuration-cache=false
# We never want to use auto-provisioning, as it breaks reproducible builds.
# This should not be a problem, because we never configure a "javaRepositories"
# item to tell Gradle where to auto-provision the toolchain from, but adding
# this flag adds an extra layer of protection.
# See: https://docs.gradle.org/current/userguide/toolchains.html#sub:disable_auto_provision
org.gradle.java.installations.auto-download=false

# Uncomment these to build libsignal from source.
# libsignalClientPath=../libsignal

# Temporarily disable dependency verification for development
org.gradle.dependency.verification=off

# Disable kapt K2 implementation
kapt.use.k2=false
kapt.use.k2.processor=false

# Set options for Kotlin 2.0 compatibility with kapt
kapt.kotlin.generated=build/generated/kapt/
kotlin.incremental=false
kapt.incremental.apt=false
kapt.include.compile.classpath=false
org.jetbrains.kotlin.kapt.classloaders.cache.size=5
kapt.use.worker.api=false
org.jetbrains.kotlin.kapt.enableKapt2xLanguageVersionsOption=true
